apiVersion: v1
kind: Service
metadata:
  name: druid-broker-svc
  labels:
    app: druid-broker
spec:
  ports:
  - name: client
    port: 8080
    protocol: TCP
  selector:
    app: druid
    component: druid-broker
  type: LoadBalancer
