apiVersion: v1
kind: Service
metadata:
  name: druid-coordinator-svc
  labels:
    app: druid-coordinator
spec:
  ports:
  - name: client
    port: 8081
    protocol: TCP
  selector:
    app: druid
    component: druid-coordinator
